
GET http://localhost:3031

###
GET http://localhost:3031/user/fetchAllUsers

###
GET http://localhost:3031/user/

###
POST http://localhost:3031/user/addUser

###
PUT  http://localhost:3031/user/updateUser/

###
DELETE  http://localhost:3031/user/deleteUser/
